# Test configuration file
# @author <a href="https://github.com/liyupi">Programmer Yupi</a>
# @from <a href="https://yupi.icu">Code Navigation Community</a>
server:
  port: 8101
spring:
  # Database configuration
  # TODO: replace with your own configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open_api
    username: root
    password: 123456
  # Redis configuration
  # TODO: replace with your own configuration
  redis:
    database: 1
    host: localhost
    port: 6379
    timeout: 5000
    password: 123456
