# Shared configuration file
# @author <a href="https://github.com/liyupi">Programmer Yupi</a>
# @from <a href="https://yupi.icu">Code Navigation Community</a>
spring:
  application:
    name: openapi-backend
  # Default dev profile
  profiles:
    active: dev
  # Enable Swagger 3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Session configuration
  session:
    # todo Uncomment to enable distributed session storage (configure Redis first).
    # store-type: redis
    # Expires in 30 days
    timeout: 2592000
  # Database configuration
  # TODO: replace with your own configuration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/open_api
    username: root
    password: 123456
  # Redis configuration
  # TODO: replace with your own configuration, then uncomment
#  redis:
#    database: 1
#    host: localhost
#    port: 6379
#    timeout: 5000
#    password: 123456
  # File upload
  servlet:
    multipart:
      # Size limit
      max-file-size: 10MB
server:
  address: 0.0.0.0
  port: 8101
  servlet:
    context-path: /api
    # Cookie expires in 30 days
    session:
      cookie:
        max-age: 2592000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # Global logic-delete field name
      logic-delete-value: 1 # Logic-deleted value (default 1)
      logic-not-delete-value: 0 # Logic-not-deleted value (default 0)

# Object storage
# TODO: replace with your own configuration
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# API documentation configuration
knife4j:
  enable: true
  openapi:
    title: "API Documentation"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.yupeng.openapi.controller
openapi:
  auth-grpc:
    port: 9091
  client:
    access-key: ak_a6ec8ee09db3066c63aebc4980d3bb2b
    secret-key: sk_954ee91d44875f13f21610af5432f59ba089db9d8c5a4ed8
    gateway-host: http://127.0.0.1:8283
    connect-timeout-millis: 3000
    read-timeout-millis: 5000
