server:
  port: 8123
  servlet:
    context-path: /api

spring:
  application:
    name: openapi-public-interface

openapi:
  client:
    access-key: ak_a6ec8ee09db3066c63aebc4980d3bb2b
    secret-key: sk_954ee91d44875f13f21610af5432f59ba089db9d8c5a4ed8
    gateway-host: http://localhost:8123
